[workspace]
members = [
  "bin",
  "configs",
  "utils",
  "app/*",
  "db",
  "migration",
]
resolver = "2"

[workspace.package]
authors = ["lingdu <waong2005@126.com>"]
edition = "2021"
homepage = "https://314.iu1314.top"
license = "Apache-2.0"
publish = false
repository = ""
version = "0.1.0"

[workspace.dependencies]
# salvo
salvo = "0"
salvo_core = "0"
# tokio
tokio = "1"
tokio-stream = "0.1"
futures-util = "0.3"

# 配置文件
toml = "0"

# 序列化
serde = "1"
serde_json = "1"
# JWT
jsonwebtoken = "9"

# 随机有序id
scru128 = "3"
#  时间
chrono = "0"
#  随机数
md5 = "0"
rand = "0"
# 验证码
math_captcha = "0"
# 
once_cell = "1"

# 错误处理
anyhow = "1"

# 计划任务
delay_timer = "0"

# 系统信息
sysinfo = "0"

user-agent-parser  = "0"

reqwest  = "0"

# 日志
time = "0"
tracing = "0"
tracing-appender = "0"
tracing-subscriber = "0"

# headers
headers = "0"

# sea-orm 数据库
sea-orm = "0"

# [workspace.dev-dependencies]

[profile.release]
codegen-units = 1 
debug = false 
lto = true 
opt-level = "z" # Optimize for size.
panic = 'abort'
