[package]
name = "configs"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
once_cell = {workspace = true}
serde = {workspace = true, features = ["derive"]}

toml = {workspace = true}
